### ISSUE TITLE
100 days of flutter widgeta

### ISSUE THREAD

**Issue by KymRhys2k22** [sanjaysanju618/100-Days-Of-Flutter-Widgets#1]

**Comment by sanjay-rb** [comment]
Hi @KymRhys2k22 ,
May I know why this issue is created, Is there any I can help you ?
Thanks & Regards,
Sanjay R B

**Comment by sanjay-rb** [comment]
Hi @KymRhys2k22 ,
As I did get any further infomation from you, I am closing the issue for now. Please reachout to us if any queries. 
Thanks & Regards,
Sanjay R B
